name: Build PDF of the Book
# This Workflow was adapted from the official docs:
# https://github.com/executablebooks/jupyter-book

on:
  push:
    branches: {{ cookiecutter.develop_branch }}

  workflow_dispatch:
  repository_dispatch:

jobs:
  pdf_from_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Set up Python {{ cookiecutter.book_python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: {{ cookiecutter.book_python_version }}


    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pushd .
        cd ..
        git clone https://github.com/executablebooks/jupyter-book.git
        cd jupyter-book
        pip install -e .[sphinx,pdflatex]
        popd


    - name: Install latex dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y     \
          texlive-latex-recommended \
          texlive-latex-extra       \
          texlive-fonts-extra       \
          fonts-freefont-otf        \
          texlive-xetex             \
          latexmk                   \
          xindy


    - name: Build PDF from LaTeX
      run: jb build . --builder pdflatex


    - uses: actions/upload-artifact@v2
      with:
        name: Book PDF
        path: _build/latex/book.pdf
